### ISSUE TITLE
Association File Name Changed

### ISSUE THREAD

**Issue by fariasfrancisco** [IHTSDO/snomed-database-loader#15]
In the `20180131` release the file `der2_cRefset_AssociationReference` was renamed to `der2_cRefset_Association` this affects POSTGRESQL's loading script (it may affect other scripts as well by I haven't tested them).

I haven't submitted a PR since my solution does not support releases with the old name.

**Comment by pgwilliams** [comment]
Thanks for that Faria, good spotting.  Yes I'll fix the MySQL version this week.
I'd be very happy to merge your PR because a) I suspected 95% of users will want to import the newest version and it's currently broken for this file and b) because the history is always available in the "full" file, I almost always work with the most recent release, even if I'm interested in what happened between previous releases.    Best Wishes, Peter

**Comment by fariasfrancisco** [comment]
No Problem. I've sent the PR.

**Comment by lookfoor** [comment]
Not all load queries (from file https://github.com/rorydavidson/SNOMED-CT-Database/blob/master/MySQL/load-mysql.sql) work with the latest version (180131) because the file names was changed.

A list of files that "are missing":
•	Delta/Refset/Content/der2_cRefset_AssociationReferenceDelta_INT_20180131.txt
•	Full/Refset/Content/der2_cRefset_AssociationReferenceFull_INT_20180131.txt
•	Snapshot/Refset/Content/der2_cRefset_AssociationReferenceSnapshot_INT_20180131.txt
•	Snapshot/Refset/Map/der2_iissscRefset_ComplexMapSnapshot_INT_20180131.txt
•	Delta/Refset/Map/der2_iissscRefset_ComplexMapDelta_INT_20180131.txt
•	Full/Refset/Map/der2_iissscRefset_ComplexMapFull_INT_20180131.txt

**Comment by pgwilliams** [comment]
Hi Lookfoor.   Thanks for spotting that, I only made the association changes to the filename in the shell script.   Have now brought "load-mysql.sql" into line.

The complex map files are missing because ICD-9 has been removed from SNOMED CT as per this deprecation notice:  https://www.snomed.org/news-articles/deprecation-notice-snomed-ct-to-icd9cm-epidemiological-and-statistical-map

Of course I don't want to remove support for that file because people will still be loading older releases, but perhaps we could make the file optional so that the redundant warning message is not displayed.
